[core]
reloadable = true
order = 0

[package]
version = "1.0.1"
category = "Simulation"
title = "ts tactile extension"
description = ""
authors = ["NVIDIA"]
repository = ""
keywords = []
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.png"


[dependencies]
"omni.kit.uiapp" = {}
"isaacsim.gui.components" = {}
"isaacsim.core.api" = {}
"isaacsim.core.prims" = {}
"isaacsim.sensors.physx" = {}
"isaacsim.storage.native" = {}

# Optional: only needed if running franka_sensor_demo.py
# "omni.physxdemos" = {optional = true}

[[python.module]]
name = "ts_tactile_extension_python"